#!/bin/bash
set -euo pipefail

chroot /sysroot

mount -t sysfs sysfs /sys
mount -t selinuxfs selinuxfs /sys/fs/selinux
/sbin/load_policy

umount /sys/fs/selinux
umount /sys

exit

systemctl --root=/sysroot enable debug-shell.service